export const sampleCourses = [
  {
    id: 1,
    code: "SS-112",
    title: "introduction to Psychology",
    semester: "Semester-8-SS-112",
    term: "Spring 2025",
    instructorName: "Komal Zafar",
  },
  {
    id: 2,
    code: "CS-430",
    title: "Database Systems",
    semester: "Semester-7-CS-430",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
  },
  {
    id: 3,
    code: "CS-440",
    title: "Software Engineering",
    semester: "Semester-7-CS-440",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
  },
  {
    id: 4,
    code: "CS-450",
    title: "Computer Networks",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
  },
  {
    id: 5,
    code: "CS-450",
    title: "Computer Networks",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
  },
  {
    id: 6,
    code: "CS-450",
    title: "Computer Networks",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
  },
  {
    id: 7,
    code: "CS-450",
    title: "Computer Networks",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
  },
  {
    id: 8 ,
    code: "CS-450",
    title: "Computer Networks",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
  }
];