export const sampleCourses = [
  {
    id: 1,
    school: "Faculty of Computer Science",
    code: "SS-112",
    title: "Introduction to Psychology",
    semester: "Semester-8-SS-112",
    term: "Spring 2025",
    instructorName: "Komal Zafar",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 2,
    school: "Faculty of Computer Science",
    code: "CS-430",
    title: "Cloud Computing",
    semester: "Semester-7-CS-430",
    term: "Fall 2024",
    instructorName: "Muhammad Shahzad Arif",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 3,
    school: "Faculty of Computer Science",
    code: "CS-440",
    title: "Cyber Security",
    semester: "Semester-7-CS-440",
    term: "Fall 2024",
    instructorName: "Dr. Muddasar Raza",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 4,
    school: "Faculty of Electrical Engineering",
    code: "CS-450",
    title: "Data Analysis and Visualization",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Muhammad Bilal",
    department: "Electrical Engineering",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 5,
    school: "Faculty of Computer Science",
    code: "CS-450",
    title: "Computer Networks",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Arshad Farhad",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 6,
    school: "Faculty of Computer Science",
    code: "CS-450",
    title: "Computer Vision",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Khawar Khurshid",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 7,
    school: "Faculty of Computer Science",
    code: "CS-450",
    title: "Digital Logic Design",
    semester: "Semester-7-CS-450",
    term: "Fall 2024",
    instructorName: "Saad Ali Malik",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 8,
    school: "Faculty of Computer Science",
    code: "CS-450",
    title: "Parallel and Distributed Systems",
    semester: "Semester-7-CS-450",
    term: "Fall 2023",
    instructorName: "Muhammad Shahzad Arif",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  },
  {
    id: 9,
    school: "Faculty of Computer Science",
    code: "CS-410",
    title: "Theory of Automata",
    semester: "Semester-5-CS-410",
    term: "Spring 2023",
    instructorName: "Muhammad Bilal",
    department: "Computer Science",
    credithours: "3+0",
    delieveryformat: "Theory",
  }
];
