export const mockCourses2 = [
    {
    "courseId": 1,
    "courseName": "Introduction to Computing",
    "courseCode": "CS101",
    "department" : "Computer Science",
    "creditHours": 3,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To introduce fundamental concepts of computing, programming, and problem-solving.",
    "notes": "First-year core course covering basic programming and computing principles.",
    "departmentId": 1
    },
    {
    "courseId": 2,
    "courseName": "Programming Fundamentals",
    "courseCode": "CS102",
    "department" : "Computer Science",
    "creditHours": 4,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To develop problem-solving skills using structured and object-oriented programming.",
    "notes": "Covers programming in C/C++ and basic algorithms.",
    "departmentId": 1
    },
    {
    "courseId": 3,
    "courseName": "Data Structures and Algorithms",
    "department" : "Computer Science",
    "courseCode": "CS201",
    "creditHours": 4,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To study fundamental data structures and their implementation in programming.",
    "notes": "Prerequisite: Programming Fundamentals. Covers stacks, queues, linked lists, trees, and graphs.",
    "departmentId": 1
    },
    {
    "courseId": 4,
    "courseName": "Object-Oriented Programming",
    "department" : "Computer Science",
    "courseCode": "CS202",
    "creditHours": 4,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To learn object-oriented programming principles and design patterns.",
    "notes": "Covers concepts like classes, objects, polymorphism, inheritance, and encapsulation.",
    "departmentId": 1
    },
    {
    "courseId": 5,
    "courseName": "Database Systems",
    "department" : "Computer Science",
    "courseCode": "CS301",
    "creditHours": 4,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To understand database design, normalization, and SQL.",
    "notes": "Covers relational databases, indexing, and transactions.",
    "departmentId": 1
    },
    {
    "courseId": 6,
    "courseName": "Operating Systems",
    "department" : "Computer Science",
    "courseCode": "CS302",
    "creditHours": 4,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To learn about process management, memory management, and file systems.",
    "notes": "Covers scheduling, synchronization, deadlocks, and virtual memory.",
    "departmentId": 1
    },
    {
    "courseId": 7,
    "courseName": "Computer Networks",
    "department" : "Computer Science",
    "courseCode": "CS303",
    "creditHours": 3,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To understand network architectures, protocols, and security.",
    "notes": "Focuses on OSI model, TCP/IP, routing, and security principles.",
    "departmentId": 1
    },
    {
    "courseId": 8,
    "courseName": "Software Engineering",
    "department" : "Computer Science",
    "courseCode": "CS304",
    "creditHours": 3,
    "isLab": false,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To introduce software development lifecycle, models, and methodologies.",
    "notes": "Covers Agile, Waterfall, and SDLC.",
    "departmentId": 1
    },
    {
    "courseId": 9,
    "courseName": "Artificial Intelligence",
    "department" : "Computer Science",
    "courseCode": "CS401",
    "creditHours": 3,
    "isLab": false,
    "isCompulsory": false,
    "isTheory": true,
    "connectedCourseId": null,
    "objective": "To study machine learning, neural networks, and AI applications.",
    "notes": "Covers intelligent agents, search algorithms, and AI programming.",
    "departmentId": 1
    },
    {
    "courseId": 10,
    "courseName": "Introduction to Computing Lab",
    "department" : "Computer Science",
    "courseCode": "CS101L",
    "creditHours": 1,
    "isLab": true,
    "isCompulsory": true,
    "isTheory": false,
    "connectedCourseId": 1,
    "objective": "Hands-on practice with basic computing concepts and programming.",
    "notes": "Includes exercises on basic programming and computer usage.",
    "departmentId": 1
    },
    {
    "courseId": 11,
    "courseName": "Programming Fundamentals Lab",
    "department" : "Computer Science",
    "courseCode": "CS102L",
    "creditHours": 1,
    "isLab": true,
    "isCompulsory": true,
    "isTheory": false,
    "connectedCourseId": 2,
    "objective": "To implement concepts learned in Programming Fundamentals.",
    "notes": "Hands-on practice with C++ programming, loops, and functions.",
    "departmentId": 1
    },
    {
    "courseId": 12,
    "courseName": "Data Structures and Algorithms Lab",
    "department" : "Computer Science",
    "courseCode": "CS201L",
    "creditHours": 1,
    "isLab": true,
    "isCompulsory": true,
    "isTheory": false,
    "connectedCourseId": 3,
    "objective": "Hands-on implementation of data structures in programming.",
    "notes": "Covers implementation of stacks, queues, trees, and graphs in C++/Python.",
    "departmentId": 1
    },
    {
    "courseId": 13,
    "courseName": "Database Systems Lab",
    "department" : "Computer Science",
    "courseCode": "CS301L",
    "creditHours": 1,
    "isLab": true,
    "isCompulsory": true,
    "isTheory": false,
    "connectedCourseId": 5,
    "objective": "Hands-on practice with database design and SQL.",
    "notes": "Covers SQL queries, normalization, and database management systems.",
    "departmentId": 1
    },
    {
    "courseId": 14,
    "courseName": "Operating Systems Lab",
    "department" : "Computer Science",
    "courseCode": "CS302L",
    "creditHours": 1,
    "isLab": true,
    "isCompulsory": true,
    "isTheory": false,
    "connectedCourseId": 6,
    "objective": "Practical implementation of OS concepts.",
    "notes": "Includes experiments on process scheduling, memory management, and file systems.",
    "departmentId": 1
    },
    {
    "courseId": 15,
    "courseName": "Computer Networks Lab",
    "department" : "Computer Science",
    "courseCode": "CS303L",
    "creditHours": 2,
    "isLab": true,
    "isCompulsory": true,
    "isTheory": true,
    "connectedCourseId": 7,
    "objective": "To practice network configurations and troubleshooting.",
    "notes": "Covers TCP/IP configuration, network protocols, and security mechanisms.",
    "departmentId": 1
    },
    {
    "courseId": 16,
    "courseName": "Object-Oriented Programming Lab",
    "department" : "Computer Science",
    "courseCode": "CS202L",
    "creditHours": 1,
    "isLab": true,
    "isCompulsory": true,
    "isTheory": false,
    "connectedCourseId": 4,
    "objective": "To implement object-oriented programming concepts.",
    "notes": "Hands-on coding with OOP concepts such as classes, inheritance, and polymorphism.",
    "departmentId": 1
    }      
  ];
  