export const mockStudents = [
    {
      id: 1,
      registrationNo: "NUM-BSCS-2024-01",
      name: "Abdul Rehman",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 2,
      registrationNo: "NUM-BSCS-2024-02",
      name: "Ahmad Ali",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 3,
      registrationNo: "NUM-BSCS-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 4,
      registrationNo: "NUM-BSCS-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 4,
      registrationNo: "NUM-BSCS-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 5,
      registrationNo: "NUM-BSCS-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 6,
      registrationNo: "NUM-BSCS-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 7,
      registrationNo: "NUM-BSCS-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSCS-Fall-2024 (B.S Computer Science)",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },

  ];