export const mockStudents = [
    {
      id: 1,
      registrationNo: "NUM-BSCS-2024-01",
      name: "Abdul Rehman",
      programBatch: "BSCS-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 2,
      registrationNo: "NUM-BSCS-2024-02",
      name: "Ahmad Ali",
      programBatch: "BSCS-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 3,
      registrationNo: "NUM-BSCS-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSCS-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 4,
      registrationNo: "NUM-BSCS-2024-21",
      name: "Ali Shoaib",
      programBatch: "BSCS-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 5,
      registrationNo: "NUM-BSEE-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BSEE-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 6,
      registrationNo: "NUM-BSEE-2024-03",
      name: "Ali Shoaib",
      programBatch: "BSEE-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 7,
      registrationNo: "NUM-BSEE-2024-03",
      name: "Abdul Rehman",
      programBatch: "BSEE-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 8,
      registrationNo: "NUM-BSEE-2024-03",
      name: "Ahmad Ali",
      programBatch: "BSEE-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 9,
      registrationNo: "NUM-BS Math-2024-01",
      name: "Abdul Rehman",
      programBatch: "BS Math-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 10,
      registrationNo: "NUM-BS Math-2024-02",
      name: "Ahmad Ali",
      programBatch: "BS Math-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 11,
      registrationNo: "NUM-BSBBA-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BS BBA-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 12,
      registrationNo: "NUM-BSBBA-2024-03",
      name: "Ali Shoaib",
      programBatch: "BS BBA-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 13,
      registrationNo: "NUM-BSBBA-2024-03",
      name: "Ahmer Sultan",
      programBatch: "BS BBA-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 14,
      registrationNo: "NUM-BSBBA-2024-03",
      name: "Ali Shoaib",
      programBatch: "BS BBA-Spring-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 15,
      registrationNo: "NUM-BS Math-2024-03",
      name: "Ahmad Ali",
      programBatch: "BS Math-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    {
      id: 16,
      registrationNo: "NUM-BS Math-2024-03",
      name: "Abdul rehman",
      programBatch: "BS Math-Fall-2024",
      section: "A",
      useInOBE: "Yes",
      status: "In-Progress",
      grade: "-",
      score: "-",
    },
    // {
    //   id: 17,
    //   registrationNo: "NUM-BSCS-2024-01",
    //   name: "Abdul Rehman",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 18,
    //   registrationNo: "NUM-BSCS-2024-02",
    //   name: "Ahmad Ali",
    //   programBatch: "BSCS-Fall-2023",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 19,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 20,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 21,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 22,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 23,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 24,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 25,
    //   registrationNo: "NUM-BSCS-2024-01",
    //   name: "Abdul Rehman",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 26,
    //   registrationNo: "NUM-BSCS-2024-02",
    //   name: "Ahmad Ali",
    //   programBatch: "BSCS-Fall-2023",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 27,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 28,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 29,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 30,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 31,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
    // {
    //   id: 32,
    //   registrationNo: "NUM-BSCS-2024-03",
    //   name: "Ahmer Sultan",
    //   programBatch: "BSCS-Fall-2024",
    //   section: "A",
    //   useInOBE: "Yes",
    //   status: "In-Progress",
    //   grade: "-",
    //   score: "-",
    // },
  ];