export const facultyData = [
    {
      id: 1,
      name: "Imran Ashraf",
      gender: "Male",
      designation: "Visiting/Part Time Faculty",
      highestDegree: "",
      facultyType: "Visiting/Part Time Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Computer Science"],
      active: "No",
      avatar: "I", // Placeholder letter avatar
    },
    {
      id: 2,
      name: "Mudassir Imran",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "PhD",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "Teacher",
      departments: ["Department of Mathematics"],
      active: "No",
      avatar: "M",
    },
    {
      id: 3,
      name: "Muhammad Ahmed",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Business Studies"],
      active: "Yes",
      avatar: "", // Default placeholder
    },
    {
      id: 4,
      name: "NAJAM UL ISLAM",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "HoD",
      departments: [
        "Department of Electrical Engineering",
        "Department of Computer Science",
        "Department of Business Studies",
        "Department of Mathematics",
      ],
      active: "Yes",
      avatar: "",
    },
  ];
  