export const mockCourses = [
    {
      name: "ACC-211 - Fall 2024",
      course: "ACC-211 - Financial Accounting II",
      semester: "Fall 2024",
      school: "Faculty of Social Sciences",
      teacher: "Zunera Batool",
      department: "Department of Business Studies",
      section: "B",
      status: "Open",
      programBatch: "BBA-Fall-2022, BBA-Fall-2020",
      useOBE: true,
    },
    {
      name: "CS-131 - Fall 2024",
      course: "CS-131 - Object Oriented Programming",
      semester: "Fall 2024",
      school: "Faculty of Computer Science",
      teacher: "Naveen Shaukat",
      department: "Department of Computer Science",
      section: "B",
      status: "Open",
      programBatch: "BSCS-Fall-2022",
      useOBE: true,
    },
    {
      name: "CS-134 - Fall 2024",
      course: "CS-134 - Probability",
      semester: "Fall 2024",
      school: "Faculty of Computer Science",
      teacher: "Faiza Ali",
      department: "Department of Computer Science",
      section: "B",
      status: "Open",
      programBatch: "BSCS-Fall-2019",
      useOBE: true,
    },
    {
      name: "SE-605 - Fall 2024",
      course: "SE-605 - Software Engineering",
      semester: "Fall 2024",
      school: "Faculty of Computer Science",
      teacher: "Asiya Batool",
      department: "Department of Computer Science",
      section: "B",
      status: "Open",
      programBatch: "BSCS-Fall-2021",
      useOBE: true,
    },
    {
      name: "ENG-110 - Fall 2024",
      course: "ENG-110 - Functional English",
      semester: "Fall 2024",
      school: "Faculty of Sciences",
      teacher: "Nida Sultan",
      department: "Department of Mathematics",
      section: "B",
      status: "Open",
      programBatch: "BSCS-Fall-2022",
      useOBE: true,
    },
  ];
  