const mockPrograms = [
    {
      id: 1,
      name: "Computer Science",
      shortName: "CS",
      sessionType: "Semester",
      department: "Science",
      programlevel: "Intermediate",
      students: 120,
      assessmentMethod: "Exams & Assignments",
      passingCriteriaInfo: "40% in each subject.",
    },
    {
        id: 2,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },
      {
        id: 3,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },
      {
        id: 4,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },
      {
        id: 5,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 6,
        name: "Business Administration",
        shortName: "BBA",
        sessionType: "Semester",
        department: "Business Studies",
        programlevel: "Normal",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 7,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 8,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 9,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 10,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 11,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 12,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 13,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 14,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 15,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 16,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 17,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 18,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 19,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 20,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 21,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 22,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      {
        id: 23,
        name: "Computer Science",
        shortName: "CS",
        sessionType: "Semester",
        department: "Science",
        programlevel: "Intermediate",
        students: 120,
        assessmentMethod: "Exams & Assignments",
        passingCriteriaInfo: "40% in each subject.",
      },

      
    ];
  
  export default mockPrograms;
  