export const facultyData = [
    {
      id: 1,
      name: "Imran Ashraf",
      gender: "Male",
      designation: "Visiting/Part Time Faculty",
      highestDegree: "",
      facultyType: "Visiting/Part Time Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Computer Science"],
      active: "No",
    },
    {
      id: 2,
      name: "Mudassir Imran",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "PhD",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "Teacher",
      departments: ["Department of Mathematics"],
      active: "No",
    },
    {
      id: 3,
      name: "Muhammad Ahmed",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Business Studies"],
      active: "Yes",
    },
    {
      id: 4,
      name: "NAJAM UL ISLAM",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "HoD",
      departments: [
        "Department of Electrical Engineering",
        "Department of Computer Science",
        "Department of Business Studies",
        "Department of Mathematics",
      ],
      active: "Yes",
    },
    {
      id: 5,
      name: "Imran Ashraf",
      gender: "Male",
      designation: "Visiting/Part Time Faculty",
      highestDegree: "",
      facultyType: "Visiting/Part Time Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Computer Science"],
      active: "No",
    },
    {
      id: 6,
      name: "Mudassir Imran",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "PhD",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "Teacher",
      departments: ["Department of Mathematics"],
      active: "No",
    },
    {
      id: 7,
      name: "Muhammad Ahmed",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Business Studies"],
      active: "Yes",
    },
    {
      id: 8,
      name: "NAJAM UL ISLAM",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "HoD",
      departments: [
        "Department of Electrical Engineering",
        "Department of Computer Science",
        "Department of Business Studies",
        "Department of Mathematics",
      ],
      active: "Yes",
    },
    {
      id: 9,
      name: "Imran Ashraf",
      gender: "Male",
      designation: "Visiting/Part Time Faculty",
      highestDegree: "",
      facultyType: "Visiting/Part Time Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Computer Science"],
      active: "No",
    },
    {
      id: 10,
      name: "Mudassir Imran",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "PhD",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "Teacher",
      departments: ["Department of Mathematics"],
      active: "No",
    },
    {
      id: 11,
      name: "Muhammad Ahmed",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Business Studies"],
      active: "Yes",
    },
    {
      id: 12,
      name: "NAJAM UL ISLAM",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "HoD",
      departments: [
        "Department of Electrical Engineering",
        "Department of Computer Science",
        "Department of Business Studies",
        "Department of Mathematics",
      ],
      active: "Yes",
    },
    {
      id: 13,
      name: "Imran Ashraf",
      gender: "Male",
      designation: "Visiting/Part Time Faculty",
      highestDegree: "",
      facultyType: "Visiting/Part Time Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Computer Science"],
      active: "No",
    },
    {
      id: 14,
      name: "Mudassir Imran",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "PhD",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "Teacher",
      departments: ["Department of Mathematics"],
      active: "No",
    },
    {
      id: 15,
      name: "Muhammad Ahmed",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Business Studies"],
      active: "Yes",
    },
    {
      id: 16,
      name: "NAJAM UL ISLAM",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "HoD",
      departments: [
        "Department of Electrical Engineering",
        "Department of Computer Science",
        "Department of Business Studies",
        "Department of Mathematics",
      ],
      active: "Yes",
    },
    {
      id: 17,
      name: "Imran Ashraf",
      gender: "Male",
      designation: "Visiting/Part Time Faculty",
      highestDegree: "",
      facultyType: "Visiting/Part Time Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Computer Science"],
      active: "No",
    },
    {
      id: 18,
      name: "Mudassir Imran",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "PhD",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "Teacher",
      departments: ["Department of Mathematics"],
      active: "No",
    },
    {
      id: 19,
      name: "Muhammad Ahmed",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Business Studies"],
      active: "Yes",
    },
    {
      id: 20,
      name: "NAJAM UL ISLAM",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "HoD",
      departments: [
        "Department of Electrical Engineering",
        "Department of Computer Science",
        "Department of Business Studies",
        "Department of Mathematics",
      ],
      active: "Yes",
    },
    {
      id: 21,
      name: "Imran Ashraf",
      gender: "Male",
      designation: "Visiting/Part Time Faculty",
      highestDegree: "",
      facultyType: "Visiting/Part Time Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Computer Science"],
      active: "No",
    },
    {
      id: 22,
      name: "Mudassir Imran",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "PhD",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "Teacher",
      departments: ["Department of Mathematics"],
      active: "No",
    },
    {
      id: 23,
      name: "Muhammad Ahmed",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "No",
      type: "Teacher",
      departments: ["Department of Business Studies"],
      active: "Yes",
    },
    {
      id: 24,
      name: "NAJAM UL ISLAM",
      gender: "Male",
      designation: "Full Time Regular Faculty",
      highestDegree: "",
      facultyType: "Full Time Regular Faculty",
      isPhD: "Yes",
      type: "HoD",
      departments: [
        "Department of Electrical Engineering",
        "Department of Computer Science",
        "Department of Business Studies",
        "Department of Mathematics",
      ],
      active: "Yes",
    },
  ];
  